// CritCare.in — Search Index
// All searchable content: topics, tools, scores, and pages
window.CRITCARE_INDEX = [
  // ── TOPICS ──────────────────────────────────────────────────────────────────
  { title: "Sepsis & Septic Shock", url: "topic-sepsis.html", type: "topic", tags: "sepsis shock vasopressors antibiotics SSC 2026 hour-1 bundle MAP lactate noradrenaline SCC crystalloids albumin beta-lactam extended infusion", desc: "SSC 2026 management, hour-1 bundle, vasopressor algorithm, antibiotics, resuscitation targets." },
  { title: "Vasopressor Dilution Guide", url: "topic-vasopressors-guide.html", type: "topic", tags: "vasopressors dilution noradrenaline adrenaline dopamine dobutamine ampoule dose table IBW infusion rate calculation", desc: "Ampoule compositions, dilution protocols, dose tables for 50–80 kg patients." },
  { title: "Vasopressors & Inotropes — Clinical", url: "topic-vasopressors.html", type: "topic", tags: "vasopressors inotropes receptor pharmacology shock cardiogenic septic dobutamine levosimendan milrinone SOAP II VASST ATHOS-3", desc: "Receptor pharmacology, shock classification, septic and cardiogenic shock algorithms." },
  { title: "Hypertensive Emergency", url: "topic-hypertensive-emergency.html", type: "topic", tags: "hypertensive emergency urgency dissection ICH stroke eclampsia labetalol nicardipine nitroprusside IV drugs ESC ESH 2023 MAP targets", desc: "BP targets by scenario, IV drug reference, ESC/ESH 2023 guidelines." },
  { title: "ARDS & Lung-Protective Ventilation", url: "topic-ards.html", type: "topic", tags: "ARDS acute respiratory distress syndrome ARDSNet tidal volume prone proning PROSEVA HFNO ECMO NMB neuromuscular blockade lung protective 6 ml/kg PBW", desc: "2023 global ARDS definition, ARDSNet protocol, prone positioning, HFNO, VV-ECMO." },
  { title: "Mechanical Ventilation", url: "topic-mechanical-ventilation.html", type: "topic", tags: "mechanical ventilation modes PEEP auto-PEEP weaning SBT extubation NIV CPAP BiPAP IBW tidal volume DOPE mnemonic AC PSV SIMV", desc: "All modes, initial settings, PEEP tables, weaning, extubation criteria, NIV." },
  { title: "Acute Severe Asthma", url: "topic-asthma.html", type: "topic", tags: "asthma status asthmaticus GINA 2026 salbutamol magnesium ketamine RSI intubation auto-PEEP heliox NIV O2 target SABA", desc: "GINA 2026 protocol, RSI with ketamine, I:E 1:3–1:5, auto-PEEP management." },
  { title: "COPD Exacerbation", url: "topic-copd.html", type: "topic", tags: "COPD exacerbation GOLD 2026 NIV controlled oxygen 88-92% steroids antibiotics bronchodilator spirometry FEV1", desc: "GOLD 2026: NIV first-line, controlled O₂ 88–92%, 5-day steroids." },
  { title: "Pneumonia, HAP & VAP", url: "topic-pneumonia-vap.html", type: "topic", tags: "pneumonia HAP VAP hospital acquired ventilator IDSA ATS 2016 CPIS MDR XDR Acinetobacter colistin MRSA linezolid vancomycin prevention bundle", desc: "IDSA/ATS 2016, VAP prevention bundle, Indian MDR antibiotics." },
  { title: "AKI & Renal Replacement Therapy", url: "topic-aki.html", type: "topic", tags: "AKI acute kidney injury KDIGO 2026 AKD CRRT renal replacement therapy citrate anticoagulation furosemide stress test biomarker staging urine output creatinine", desc: "KDIGO 2026, AKD as new entity, CRRT prescription, citrate anticoagulation." },
  { title: "Electrolyte Emergencies", url: "topic-electrolytes.html", type: "topic", tags: "electrolytes hyponatraemia hypernatraemia hypokalaemia hyperkalaemia hypomagnesaemia hypocalcaemia hypophosphataemia ODS correction formula refeeding syndrome", desc: "Hyponatraemia correction rates, hyperkalaemia algorithm, refeeding syndrome." },
  { title: "Acute Coronary Syndromes", url: "topic-acs.html", type: "topic", tags: "ACS STEMI NSTEMI unstable angina door to balloon PCI fibrinolysis GRACE score antiplatelet anticoagulation cardiogenic shock troponin ACC AHA 2025", desc: "STEMI door-to-balloon <90 min, fibrinolysis doses, GRACE score, cardiogenic shock." },
  { title: "Head Injury & TBI", url: "topic-tbi.html", type: "topic", tags: "TBI traumatic brain injury head injury BTF 2023 ICP intracranial pressure mannitol hypertonic saline levetiracetam phenytoin steroids CRASH SBP 110 neuroprotection", desc: "BTF 2023: SBP ≥110 mmHg, steroids contraindicated, ICP management." },
  { title: "Status Epilepticus", url: "topic-status-epilepticus.html", type: "topic", tags: "status epilepticus seizures midazolam lorazepam levetiracetam valproate fosphenytoin RAMPART ESETT NCS 2024 5 minute definition refractory burst suppression EEG", desc: "NCS 2024 5-minute definition, RAMPART trial, ESETT trial, refractory SE." },
  { title: "Neurocritical Care", url: "topic-neuro.html", type: "topic", tags: "neurocritical care stroke ischaemic haemorrhagic ICP brain death criteria AHA ASA NCS management algorithm drug doses", desc: "ICP management, ischaemic & haemorrhagic stroke, brain death criteria." },
  { title: "Acute ED Emergencies — Indian Context", url: "topic-ed-emergencies.html", type: "topic", tags: "emergency ABCDE RUSH protocol dyspnoea chest pain coma anaphylaxis OP poisoning organophosphate ALP aluminium phosphide snake bite malaria dengue scrub typhus tropical fever", desc: "ABCDE framework, RUSH protocol, anaphylaxis, poisoning, tropical fever." },
  { title: "Sedation, Analgesia & Delirium", url: "topic-sedation.html", type: "topic", tags: "sedation analgesia delirium PADIS 2018 RASS CPOT CAM-ICU propofol dexmedetomidine midazolam fentanyl morphine ABCDEF bundle eCASH delirium management", desc: "PADIS 2018, ABCDEF bundle, eCASH, RASS/CPOT, CAM-ICU." },
  { title: "Acute Liver Failure", url: "topic-alf.html", type: "topic", tags: "acute liver failure ALF hepatic failure King's College Criteria hepatic encephalopathy coagulopathy cerebral oedema transplant APASL EASL NAC NAcetylcysteine paracetamol ammonia", desc: "King's College Criteria, hepatic encephalopathy grading, coagulopathy management." },
  { title: "Toxicology in ICU", url: "topic-toxicology.html", type: "topic", tags: "toxicology poisoning OP organophosphate atropine pralidoxime paracetamol NAC antidotes dialysable toxins ALP aluminium phosphide snake bite Indian context", desc: "OP poisoning, paracetamol NAC, antidote quick reference, dialysable toxins." },
  // ── NEW TOPICS ──────────────────────────────────────────────────────────────
  { title: "Post-Cardiac Arrest Care & ROSC", url: "topic-rosc.html", type: "topic", tags: "cardiac arrest ROSC return spontaneous circulation post arrest care TTM targeted temperature management fever avoidance PCAS coronary angiography STEMI TOMAHAWK COACT AHA 2025 neuroprognostication EEG SSEP NSE TTM2", desc: "AHA 2025 guidelines: fever avoidance ≤37.5°C, coronary angio timing, neuroprognostication at 72h." },
  { title: "Endocrine Emergencies — DKA, HHS, Thyroid Storm", url: "topic-endocrine.html", type: "topic", tags: "DKA diabetic ketoacidosis HHS hyperosmolar hyperglycaemic state endocrine emergency insulin potassium ADA 2024 thyroid storm Burch-Wartofsky adrenal crisis hydrocortisone PTU methimazole terlipressin SGLT2 euglycaemic DKA bicarb bicarbonate anion gap ketones", desc: "ADA 2024 DKA protocol, HHS management, thyroid storm, adrenal crisis." },
  { title: "GI Emergencies — GI Bleed & Pancreatitis", url: "topic-gi.html", type: "topic", tags: "GI bleed upper lower UGIB LGIB variceal non-variceal Blatchford score Rockford octreotide terlipressin pancreatitis acute severe CTSI Revised Atlanta enteral nutrition early feeding LR lactated Ringer's ASGE 2021 ACG 2013 stress ulcer SUP PPI", desc: "GI bleed management (Blatchford, octreotide), pancreatitis severity, early EN, SUP guidelines." },
  { title: "Pulmonary Embolism & VTE", url: "topic-pulmonary-embolism.html", type: "topic", tags: "pulmonary embolism PE VTE venous thromboembolism DVT deep vein thrombosis massive submassive high risk intermediate sPESI PESI Wells score D-dimer CTPA RV strain McConnell thrombolysis alteplase tPA tenecteplase heparin DOAC apixaban rivaroxaban anticoagulation ESC 2019 PEITHO IVC filter prophylaxis", desc: "ESC 2019 risk stratification, sPESI, RV strain, thrombolysis (PEITHO), catheter-directed therapy, DVT prophylaxis." },
  { title: "Atrial Fibrillation & Tachyarrhythmias in the ICU", url: "topic-arrhythmias.html", type: "topic", tags: "atrial fibrillation AF flutter SVT VT ventricular tachycardia arrhythmia tachyarrhythmia rate control rhythm control DC cardioversion synchronised ACLS unstable metoprolol diltiazem amiodarone digoxin adenosine magnesium torsades polymorphic CHA2DS2-VASc anticoagulation new onset sepsis WPW", desc: "Stable vs unstable, ACLS cardioversion, AF rate vs rhythm control, SVT/VT, torsades, anticoagulation." },
  { title: "Acid–Base Disorders", url: "topic-acid-base.html", type: "topic", tags: "acid base disorders metabolic acidosis alkalosis respiratory anion gap delta delta ratio Winter's formula osmolar gap MUDPILES GOLDMARK NAGMA hyperchloraemic Stewart strong ion difference SID albumin corrected compensation high anion gap interpretation 6 step systematic", desc: "Systematic 6-step interpretation, Winter's formula, anion gap, delta-delta, osmolar gap, MUDPILES, Stewart approach." },
  { title: "Nutrition in Critical Illness", url: "topic-nutrition.html", type: "topic", tags: "nutrition critical illness enteral parenteral EN PN early feeding ASPEN ESPEN 2022 calories protein 1.2 2.0 g/kg refeeding syndrome thiamine phosphate hypophosphataemia gastric residual volume GRV EPaNIC NUTRIREA EFFORT protein indirect calorimetry overfeeding RQ", desc: "ASPEN/ESPEN 2022 targets, early enteral nutrition, parenteral timing (EPaNIC), refeeding syndrome, protein dosing." },
  { title: "Transfusion & Coagulopathy in the ICU", url: "topic-transfusion.html", type: "topic", tags: "transfusion blood RBC restrictive threshold Hb 70 80 TRICC TRISS TRIGGER massive transfusion protocol MTP 1:1:1 PROPPR tranexamic acid TXA CRASH-2 DIC disseminated intravascular coagulation thrombocytopenia HIT 4Ts platelets FFP cryoprecipitate fibrinogen PCC warfarin reversal idarucizumab andexanet TACO TRALI haemolytic reaction AABB", desc: "Restrictive Hb thresholds, massive transfusion 1:1:1, TXA, DIC, HIT, anticoagulant reversal, TACO vs TRALI." },

  // ── EMERGENCY MEDICINE TOPICS ─────────────────────────────────────────────────
  { title: "Anaphylaxis", url: "topic-anaphylaxis.html", type: "topic", tags: "anaphylaxis allergic reaction adrenaline epinephrine IM intramuscular 1:1000 anterolateral thigh refractory infusion biphasic reaction positioning supine WAO 2020 Resuscitation Council UK 2021 EAACI glucagon beta-blocker angioedema bronchospasm distributive shock tryptase auto-injector EpiPen Tintinalli Rosen", desc: "WAO/RCUK criteria, IM adrenaline first-line, positioning, refractory anaphylaxis, biphasic reactions, beta-blocked patients." },
  { title: "Snakebite & Envenomation", url: "topic-snakebite.html", type: "topic", tags: "snakebite snake bite envenomation antivenom anti-snake venom ASV polyvalent Big Four cobra krait Russell's viper saw-scaled neurotoxic haemotoxic 20-WBCT 20 minute whole blood clotting test coagulopathy VICC neostigmine atropine ptosis National Snakebite Management Protocol WHO SEARO ICMR India eschar AKI Tintinalli Rosen", desc: "India's Big Four, 20-WBCT, ASV dosing, neurotoxic vs haemotoxic syndromes, neostigmine, ASV reactions." },
  { title: "Trauma — Primary Survey & Resuscitation", url: "topic-trauma.html", type: "topic", tags: "trauma primary survey ATLS C-ABCDE catastrophic haemorrhage damage control resuscitation permissive hypotension massive transfusion 1:1:1 PROPPR TXA tranexamic acid CRASH-2 CRASH-3 FAST tension pneumothorax pelvic binder lethal triad hypothermia acidosis coagulopathy haemorrhagic shock Tintinalli Rosen", desc: "ATLS primary survey, damage control resuscitation, permissive hypotension, massive transfusion, TXA, tension pneumothorax." },
  { title: "Environmental Emergencies — Heat Stroke, Hypothermia, Drowning", url: "topic-environmental.html", type: "topic", tags: "environmental heat stroke hyperthermia cooling cold water immersion exertional classic antipyretics hypothermia rewarming afterdrop not dead until warm and dead drowning electrical lightning injury rhabdomyolysis Wilderness Medical Society ERC 2021 NDMA heat wave serotonin syndrome neuroleptic malignant Tintinalli Rosen", desc: "Heat stroke (cool first, target 39C), accidental hypothermia rewarming, drowning, electrical & lightning injury." },
  { title: "Acute Undifferentiated Febrile Illness — Tropical Fever", url: "topic-febrile-illness.html", type: "topic", tags: "fever undifferentiated febrile illness AUFI tropical dengue warning signs plasma leak haematocrit malaria falciparum IV artesunate scrub typhus eschar doxycycline leptospirosis Weil's enteric fever typhoid ceftriaxone thrombocytopenia ICMR NVBDCP NCVBDC WHO empirical therapy co-infection Tintinalli Rosen", desc: "Tropical fever approach — dengue, severe malaria (artesunate), scrub typhus (doxycycline), leptospirosis, empirical therapy." },

  { title: "Shock — Classification & Approach", url: "topic-shock.html", type: "topic", tags: "shock hypovolaemic cardiogenic distributive obstructive haemodynamic profile SVR cardiac output preload RUSH ultrasound pump tank pipes MAP lactate clearance capillary refill ANDROMEDA undifferentiated shock tissue hypoperfusion DO2 oxygen delivery", desc: "The 4 types of shock, haemodynamic profiles, RUSH exam, MAP/lactate targets, matching treatment to mechanism." },
  { title: "Haemodynamic Monitoring & Fluid Responsiveness", url: "topic-haemodynamic-monitoring.html", type: "topic", tags: "haemodynamic monitoring fluid responsiveness CVP central venous pressure PPV SVV pulse pressure variation stroke volume variation passive leg raise PLR fluid challenge Frank-Starling ScvO2 SvO2 lactate arterial line pulse contour PiCCO FloTrac echo VTI pulmonary artery catheter de-resuscitation", desc: "Why CVP fails, dynamic indices (PPV/SVV), passive leg raise, fluid challenge, when to stop fluids." },
  { title: "Acute Ischaemic Stroke", url: "topic-stroke.html", type: "topic", tags: "acute ischaemic stroke CVA thrombolysis alteplase tenecteplase tPA NIHSS thrombectomy endovascular DAWN DEFUSE-3 large vessel occlusion LVO penumbra last known well door to needle blood pressure 185/110 perfusion imaging CT mimic hypoglycaemia posterior circulation basilar HINTS AHA ASA 2019 time is brain", desc: "NIHSS, thrombolysis ≤4.5h, thrombectomy windows to 24h, BP targets, exclusions, stroke mimics, posterior stroke." },
  { title: "Acute Poisoning — Toxidromes & Antidotes", url: "topic-poisoning.html", type: "topic", tags: "poisoning overdose toxidrome cholinergic anticholinergic sympathomimetic opioid sedative activated charcoal decontamination gastric lavage whole bowel irrigation haemodialysis urinary alkalinisation antidote naloxone NAC atropine pralidoxime sodium bicarbonate TCA flumazenil fomepizole digoxin Fab intralipid organophosphate aluminium phosphide celphos paraquat paracetamol salicylate NPIC", desc: "The 5 toxidromes, decontamination, enhanced elimination, antidote quick-reference, Indian poisons (OP, ALP, paraquat)." },

  { title: "Difficult Airway Management", url: "topic-difficult-airway.html", type: "topic", tags: "difficult airway intubation DAS 2025 AIDAA 2025 India Code D ASA 2022 CICO cannot intubate cannot oxygenate complete ventilation failure front of neck access FONA cricothyroidotomy scalpel bougie tube videolaryngoscopy peroxygenation apnoeic oxygen first pass LEMON MACOCHA Mallampati awake intubation RSI supraglottic SGA i-gel Vortex NAP4 capnography sugammadex extubation physiologically difficult", desc: "DAS 2025 & AIDAA 2025 — Plan A–D, peroxygenation, Code D, non-hierarchical rescue, CICO & surgical cricothyroidotomy." },
  { title: "ACLS & BLS — Cardiac Arrest", url: "topic-acls-bls.html", type: "topic", tags: "ACLS BLS CPR cardiac arrest resuscitation AHA 2020 2025 defibrillation VF VT pulseless PEA asystole shockable adrenaline epinephrine amiodarone lidocaine Hs Ts reversible causes ROSC bradycardia tachycardia atropine pacing synchronised cardioversion DSED double sequential defibrillation naloxone TTM capnography chain of survival ILCOR ERC", desc: "High-quality CPR, the arrest algorithm, drugs & defibrillation, Hs & Ts, peri-arrest brady/tachy, and AHA 2020→latest changes." },

  // ── TOOLS ───────────────────────────────────────────────────────────────────
  { title: "Flashcards — Rapid Revision", url: "flashcards.html", type: "tool", tags: "flashcards revision flip cards quick recall sepsis ARDS ACLS difficult airway electrolytes acid-base shock DKA exam prep memorise high yield", desc: "Concise flip-card decks for fast revision — sepsis, ARDS, ACLS, airway, electrolytes, acid-base, shock, DKA." },
  { title: "Drug Reference Guide — ICU & Emergency", url: "drug-reference.html", type: "tool", tags: "drug reference guide ICU emergency injectable concentration dose vial KCl potassium magnesium sodium bicarbonate hypertonic saline calcium gluconate chloride dextrose noradrenaline adrenaline vasopressin propofol midazolam fentanyl ketamine rocuronium cisatracurium amiodarone atropine adenosine furosemide mannitol naloxone hydrocortisone correction calculator side effects", desc: "ICU & emergency drugs — concentrations, correction formulas, dose calculators, vial guide, side effects." },
  { title: "ABG Calculator & Interpreter", url: "abg-calculator.html", type: "tool", tags: "ABG arterial blood gas pH PaO2 PaCO2 bicarbonate acid base metabolic acidosis alkalosis respiratory compensation Winters formula", desc: "Interpret ABGs — pH, gas, metabolic/respiratory compensation, ROME system." },
  { title: "CritCare AI — ICU Decision Support", url: "ai-tool.html", type: "tool", tags: "AI artificial intelligence decision support chatbot clinical management sepsis ARDS ventilation pneumonia ICU bedside tool", desc: "AI-powered ICU assistant — enter clinical summary, get structured management plan." },
  { title: "Clinical Score Calculators", url: "scores.html", type: "tool", tags: "scores calculators SOFA qSOFA GCS RASS CPOT CURB-65 NEWS2 Wells DVT PE HEART score DECAF NIHSS MELD Child-Pugh Ranson GRACE", desc: "24+ clinical calculators: SOFA, qSOFA, GCS, Wells DVT/PE, GRACE, MELD, NIHSS and more." },
  { title: "eGFR & Creatinine Clearance Calculator", url: "scores.html", type: "tool", tags: "eGFR CKD-EPI 2021 race-free creatinine clearance CrCl Cockcroft-Gault Cockcroft Gault GFR kidney function CKD stage KDIGO NKF ASN renal drug dosing", desc: "CKD-EPI 2021 race-free eGFR + Cockcroft-Gault creatinine clearance with CKD staging." },
  { title: "Electrolyte Deficit Calculators — Na, K, Ca", url: "scores.html", type: "tool", tags: "electrolyte calculator sodium correction Adrogue Madias hyponatraemia free water deficit hypernatraemia potassium deficit corrected calcium albumin magnesium replacement ODS 3% NaCl TBW", desc: "Sodium correction (Adrogué–Madias), free-water deficit, potassium deficit, corrected calcium." },

  // ── SCORE SECTIONS ──────────────────────────────────────────────────────────
  { title: "SOFA Score", url: "scores.html", type: "score", tags: "SOFA sequential organ failure assessment score sepsis organ dysfunction ICU mortality", desc: "Organ dysfunction across 6 systems; SOFA ≥2 = sepsis definition." },
  { title: "qSOFA Score", url: "scores.html", type: "score", tags: "qSOFA quick sepsis bedside altered mentation respiratory rate systolic BP quick screening", desc: "3-variable bedside sepsis screen (RR, SBP, altered consciousness)." },
  { title: "Glasgow Coma Scale (GCS)", url: "scores.html", type: "score", tags: "GCS Glasgow Coma Scale neurological consciousness eyes verbal motor score brain injury", desc: "Standard neurological assessment — eyes, verbal, motor." },
  { title: "RASS — Sedation Scale", url: "scores.html", type: "score", tags: "RASS Richmond Agitation Sedation Scale sedation depth level ICU ventilator", desc: "Sedation depth from +4 (combative) to −5 (unarousable)." },
  { title: "CURB-65 — Pneumonia Severity", url: "scores.html", type: "score", tags: "CURB-65 pneumonia severity community acquired hospital admission urea respiratory rate blood pressure age", desc: "Pneumonia severity — 5 variables, predicts 30-day mortality." },
  { title: "Wells Score — DVT", url: "scores.html", type: "score", tags: "Wells DVT deep vein thrombosis probability pretest probability ultrasound D-dimer", desc: "Pre-test probability for DVT — stratifies to low/moderate/high." },
  { title: "Wells Score — PE", url: "scores.html", type: "score", tags: "Wells PE pulmonary embolism probability pretest CTPA CTPE D-dimer", desc: "Pre-test probability for pulmonary embolism." },
  { title: "HEART Score", url: "scores.html", type: "score", tags: "HEART score ACS chest pain risk stratification troponin ECG history risk factors emergency", desc: "HEART score for early discharge decision in chest pain patients." },
  { title: "GRACE Score", url: "scores.html", type: "score", tags: "GRACE ACS NSTEMI mortality in-hospital 6-month risk stratification cardiac", desc: "GRACE score for ACS mortality prediction at 6 months." },
  { title: "NIHSS — Stroke Scale", url: "scores.html", type: "score", tags: "NIHSS National Institutes Health Stroke Scale ischaemic stroke thrombolysis severity deficit", desc: "Stroke severity — guides thrombolysis decisions." },
  { title: "MELD Score", url: "scores.html", type: "score", tags: "MELD liver disease model end-stage cirrhosis transplant priority creatinine bilirubin INR", desc: "Model for End-Stage Liver Disease — guides transplant listing." },
  { title: "Child-Pugh Score", url: "scores.html", type: "score", tags: "Child-Pugh cirrhosis liver disease classification prognosis ascites encephalopathy albumin bilirubin PT", desc: "Liver disease severity A/B/C — classic prognostic tool." },
  { title: "Ranson's Criteria — Pancreatitis", url: "scores.html", type: "score", tags: "Ranson pancreatitis severity acute mortality 11 criteria glucose WBC LDH AST age", desc: "Pancreatitis severity — 11 criteria scored over 48h." },
  { title: "P/F Ratio — Oxygenation", url: "scores.html", type: "score", tags: "PF ratio PaO2 FiO2 ARDS oxygenation index lung injury", desc: "PaO₂/FiO₂ ratio — Berlin ARDS definition thresholds." },
  { title: "IBW & Tidal Volume Calculator", url: "scores.html", type: "score", tags: "IBW ideal body weight tidal volume ventilator settings 6 ml/kg ARDS lung protective height gender", desc: "Calculate IBW and 6 ml/kg tidal volume for ventilator setup." },

  // ── DNB PAPERS ──────────────────────────────────────────────────────────────
  { title: "DNB Anaesthesiology — June 2026 Solved Papers", url: "dnb.html", type: "tool", tags: "DNB anaesthesia anesthesia solved papers June 2026 previous year questions answers MCQ long answer short answer exam preparation Paper 1 2 3 4", desc: "40 fully solved DNB Anaesthesiology June 2026 questions — model answers, key points, exam tips, extra marks content." },

  // ── PAGES ───────────────────────────────────────────────────────────────────
  { title: "About Dr. Anmol Srivastava", url: "about.html", type: "page", tags: "about Dr Anmol Srivastava emergency medicine SGPGIMS ICU anaesthesiology critical care contact", desc: "Dr. Anmol Srivastava — Senior Resident Emergency Medicine, SGPGIMS Lucknow." },
  { title: "All ICU Topics", url: "topics.html", type: "page", tags: "topics ICU reference library clinical cardiology respiratory renal neuro infections supportive care", desc: "Full topic library — 22+ evidence-based critical care topics." },
];
