// CritCare.in — Search Index
// All searchable content: topics, tools, scores, and pages
window.CRITCARE_INDEX = [
  // ── TOPICS ──────────────────────────────────────────────────────────────────
  { title: "Sepsis & Septic Shock", url: "topic-sepsis.html", type: "topic", tags: "sepsis shock vasopressors antibiotics SSC 2026 hour-1 bundle MAP lactate noradrenaline SCC crystalloids albumin beta-lactam extended infusion", desc: "SSC 2026 management, hour-1 bundle, vasopressor algorithm, antibiotics, resuscitation targets." },
  { title: "Vasopressor Dilution Guide", url: "topic-vasopressors-guide.html", type: "topic", tags: "vasopressors dilution noradrenaline adrenaline dopamine dobutamine ampoule dose table IBW infusion rate calculation", desc: "Ampoule compositions, dilution protocols, dose tables for 50–80 kg patients." },
  { title: "Vasopressors & Inotropes — Clinical", url: "topic-vasopressors.html", type: "topic", tags: "vasopressors inotropes receptor pharmacology shock cardiogenic septic dobutamine levosimendan milrinone SOAP II VASST ATHOS-3", desc: "Receptor pharmacology, shock classification, septic and cardiogenic shock algorithms." },
  { title: "Hypertensive Emergency", url: "topic-hypertensive-emergency.html", type: "topic", tags: "hypertensive emergency urgency dissection ICH stroke eclampsia labetalol nicardipine nitroprusside IV drugs ESC ESH 2023 MAP targets", desc: "BP targets by scenario, IV drug reference, ESC/ESH 2023 guidelines." },
  { title: "ARDS & Lung-Protective Ventilation", url: "topic-ards.html", type: "topic", tags: "ARDS acute respiratory distress syndrome ARDSNet tidal volume prone proning PROSEVA HFNO ECMO NMB neuromuscular blockade lung protective 6 ml/kg PBW", desc: "2023 global ARDS definition, ARDSNet protocol, prone positioning, HFNO, VV-ECMO." },
  { title: "Mechanical Ventilation", url: "topic-mechanical-ventilation.html", type: "topic", tags: "mechanical ventilation modes PEEP auto-PEEP weaning SBT extubation NIV CPAP BiPAP IBW tidal volume DOPE mnemonic AC PSV SIMV", desc: "All modes, initial settings, PEEP tables, weaning, extubation criteria, NIV." },
  { title: "Acute Severe Asthma", url: "topic-asthma.html", type: "topic", tags: "asthma status asthmaticus GINA 2026 salbutamol magnesium ketamine RSI intubation auto-PEEP heliox NIV O2 target SABA", desc: "GINA 2026 protocol, RSI with ketamine, I:E 1:3–1:5, auto-PEEP management." },
  { title: "COPD Exacerbation", url: "topic-copd.html", type: "topic", tags: "COPD exacerbation GOLD 2026 NIV controlled oxygen 88-92% steroids antibiotics bronchodilator spirometry FEV1", desc: "GOLD 2026: NIV first-line, controlled O₂ 88–92%, 5-day steroids." },
  { title: "Pneumonia, HAP & VAP", url: "topic-pneumonia-vap.html", type: "topic", tags: "pneumonia HAP VAP hospital acquired ventilator IDSA ATS 2016 CPIS MDR XDR Acinetobacter colistin MRSA linezolid vancomycin prevention bundle", desc: "IDSA/ATS 2016, VAP prevention bundle, Indian MDR antibiotics." },
  { title: "AKI & Renal Replacement Therapy", url: "topic-aki.html", type: "topic", tags: "AKI acute kidney injury KDIGO 2026 AKD CRRT renal replacement therapy citrate anticoagulation furosemide stress test biomarker staging urine output creatinine", desc: "KDIGO 2026, AKD as new entity, CRRT prescription, citrate anticoagulation." },
  { title: "Electrolyte Emergencies", url: "topic-electrolytes.html", type: "topic", tags: "electrolytes hyponatraemia hypernatraemia hypokalaemia hyperkalaemia hypomagnesaemia hypocalcaemia hypophosphataemia ODS correction formula refeeding syndrome", desc: "Hyponatraemia correction rates, hyperkalaemia algorithm, refeeding syndrome." },
  { title: "Acute Coronary Syndromes", url: "topic-acs.html", type: "topic", tags: "ACS STEMI NSTEMI unstable angina door to balloon PCI fibrinolysis GRACE score antiplatelet anticoagulation cardiogenic shock troponin ACC AHA 2025", desc: "STEMI door-to-balloon <90 min, fibrinolysis doses, GRACE score, cardiogenic shock." },
  { title: "Head Injury & TBI", url: "topic-tbi.html", type: "topic", tags: "TBI traumatic brain injury head injury BTF 2023 ICP intracranial pressure mannitol hypertonic saline levetiracetam phenytoin steroids CRASH SBP 110 neuroprotection", desc: "BTF 2023: SBP ≥110 mmHg, steroids contraindicated, ICP management." },
  { title: "Status Epilepticus", url: "topic-status-epilepticus.html", type: "topic", tags: "status epilepticus seizures midazolam lorazepam levetiracetam valproate fosphenytoin RAMPART ESETT NCS 2024 5 minute definition refractory burst suppression EEG", desc: "NCS 2024 5-minute definition, RAMPART trial, ESETT trial, refractory SE." },
  { title: "Neurocritical Care", url: "topic-neuro.html", type: "topic", tags: "neurocritical care stroke ischaemic haemorrhagic ICP brain death criteria AHA ASA NCS management algorithm drug doses", desc: "ICP management, ischaemic & haemorrhagic stroke, brain death criteria." },
  { title: "Acute ED Emergencies — Indian Context", url: "topic-ed-emergencies.html", type: "topic", tags: "emergency ABCDE RUSH protocol dyspnoea chest pain coma anaphylaxis OP poisoning organophosphate ALP aluminium phosphide snake bite malaria dengue scrub typhus tropical fever", desc: "ABCDE framework, RUSH protocol, anaphylaxis, poisoning, tropical fever." },
  { title: "Sedation, Analgesia & Delirium", url: "topic-sedation.html", type: "topic", tags: "sedation analgesia delirium PADIS 2018 RASS CPOT CAM-ICU propofol dexmedetomidine midazolam fentanyl morphine ABCDEF bundle eCASH delirium management", desc: "PADIS 2018, ABCDEF bundle, eCASH, RASS/CPOT, CAM-ICU." },
  { title: "Acute Liver Failure", url: "topic-alf.html", type: "topic", tags: "acute liver failure ALF hepatic failure King's College Criteria hepatic encephalopathy coagulopathy cerebral oedema transplant APASL EASL NAC NAcetylcysteine paracetamol ammonia", desc: "King's College Criteria, hepatic encephalopathy grading, coagulopathy management." },
  { title: "Toxicology in ICU", url: "topic-toxicology.html", type: "topic", tags: "toxicology poisoning OP organophosphate atropine pralidoxime paracetamol NAC antidotes dialysable toxins ALP aluminium phosphide snake bite Indian context", desc: "OP poisoning, paracetamol NAC, antidote quick reference, dialysable toxins." },
  // ── NEW TOPICS ──────────────────────────────────────────────────────────────
  { title: "Post-Cardiac Arrest Care & ROSC", url: "topic-rosc.html", type: "topic", tags: "cardiac arrest ROSC return spontaneous circulation post arrest care TTM targeted temperature management fever avoidance PCAS coronary angiography STEMI TOMAHAWK COACT AHA 2025 neuroprognostication EEG SSEP NSE TTM2", desc: "AHA 2025 guidelines: fever avoidance ≤37.5°C, coronary angio timing, neuroprognostication at 72h." },
  { title: "Endocrine Emergencies — DKA, HHS, Thyroid Storm", url: "topic-endocrine.html", type: "topic", tags: "DKA diabetic ketoacidosis HHS hyperosmolar hyperglycaemic state endocrine emergency insulin potassium ADA 2024 thyroid storm Burch-Wartofsky adrenal crisis hydrocortisone PTU methimazole terlipressin SGLT2 euglycaemic DKA bicarb bicarbonate anion gap ketones", desc: "ADA 2024 DKA protocol, HHS management, thyroid storm, adrenal crisis." },
  { title: "GI Emergencies — GI Bleed & Pancreatitis", url: "topic-gi.html", type: "topic", tags: "GI bleed upper lower UGIB LGIB variceal non-variceal Blatchford score Rockford octreotide terlipressin pancreatitis acute severe CTSI Revised Atlanta enteral nutrition early feeding LR lactated Ringer's ASGE 2021 ACG 2013 stress ulcer SUP PPI", desc: "GI bleed management (Blatchford, octreotide), pancreatitis severity, early EN, SUP guidelines." },

  // ── TOOLS ───────────────────────────────────────────────────────────────────
  { title: "ABG Calculator & Interpreter", url: "abg-calculator.html", type: "tool", tags: "ABG arterial blood gas pH PaO2 PaCO2 bicarbonate acid base metabolic acidosis alkalosis respiratory compensation Winters formula", desc: "Interpret ABGs — pH, gas, metabolic/respiratory compensation, ROME system." },
  { title: "CritCare AI — ICU Decision Support", url: "ai-tool.html", type: "tool", tags: "AI artificial intelligence decision support chatbot clinical management sepsis ARDS ventilation pneumonia ICU bedside tool", desc: "AI-powered ICU assistant — enter clinical summary, get structured management plan." },
  { title: "Clinical Score Calculators", url: "scores.html", type: "tool", tags: "scores calculators SOFA qSOFA GCS RASS CPOT CURB-65 NEWS2 Wells DVT PE HEART score DECAF NIHSS MELD Child-Pugh Ranson GRACE", desc: "24+ clinical calculators: SOFA, qSOFA, GCS, Wells DVT/PE, GRACE, MELD, NIHSS and more." },

  // ── SCORE SECTIONS ──────────────────────────────────────────────────────────
  { title: "SOFA Score", url: "scores.html", type: "score", tags: "SOFA sequential organ failure assessment score sepsis organ dysfunction ICU mortality", desc: "Organ dysfunction across 6 systems; SOFA ≥2 = sepsis definition." },
  { title: "qSOFA Score", url: "scores.html", type: "score", tags: "qSOFA quick sepsis bedside altered mentation respiratory rate systolic BP quick screening", desc: "3-variable bedside sepsis screen (RR, SBP, altered consciousness)." },
  { title: "Glasgow Coma Scale (GCS)", url: "scores.html", type: "score", tags: "GCS Glasgow Coma Scale neurological consciousness eyes verbal motor score brain injury", desc: "Standard neurological assessment — eyes, verbal, motor." },
  { title: "RASS — Sedation Scale", url: "scores.html", type: "score", tags: "RASS Richmond Agitation Sedation Scale sedation depth level ICU ventilator", desc: "Sedation depth from +4 (combative) to −5 (unarousable)." },
  { title: "CURB-65 — Pneumonia Severity", url: "scores.html", type: "score", tags: "CURB-65 pneumonia severity community acquired hospital admission urea respiratory rate blood pressure age", desc: "Pneumonia severity — 5 variables, predicts 30-day mortality." },
  { title: "Wells Score — DVT", url: "scores.html", type: "score", tags: "Wells DVT deep vein thrombosis probability pretest probability ultrasound D-dimer", desc: "Pre-test probability for DVT — stratifies to low/moderate/high." },
  { title: "Wells Score — PE", url: "scores.html", type: "score", tags: "Wells PE pulmonary embolism probability pretest CTPA CTPE D-dimer", desc: "Pre-test probability for pulmonary embolism." },
  { title: "HEART Score", url: "scores.html", type: "score", tags: "HEART score ACS chest pain risk stratification troponin ECG history risk factors emergency", desc: "HEART score for early discharge decision in chest pain patients." },
  { title: "GRACE Score", url: "scores.html", type: "score", tags: "GRACE ACS NSTEMI mortality in-hospital 6-month risk stratification cardiac", desc: "GRACE score for ACS mortality prediction at 6 months." },
  { title: "NIHSS — Stroke Scale", url: "scores.html", type: "score", tags: "NIHSS National Institutes Health Stroke Scale ischaemic stroke thrombolysis severity deficit", desc: "Stroke severity — guides thrombolysis decisions." },
  { title: "MELD Score", url: "scores.html", type: "score", tags: "MELD liver disease model end-stage cirrhosis transplant priority creatinine bilirubin INR", desc: "Model for End-Stage Liver Disease — guides transplant listing." },
  { title: "Child-Pugh Score", url: "scores.html", type: "score", tags: "Child-Pugh cirrhosis liver disease classification prognosis ascites encephalopathy albumin bilirubin PT", desc: "Liver disease severity A/B/C — classic prognostic tool." },
  { title: "Ranson's Criteria — Pancreatitis", url: "scores.html", type: "score", tags: "Ranson pancreatitis severity acute mortality 11 criteria glucose WBC LDH AST age", desc: "Pancreatitis severity — 11 criteria scored over 48h." },
  { title: "P/F Ratio — Oxygenation", url: "scores.html", type: "score", tags: "PF ratio PaO2 FiO2 ARDS oxygenation index lung injury", desc: "PaO₂/FiO₂ ratio — Berlin ARDS definition thresholds." },
  { title: "IBW & Tidal Volume Calculator", url: "scores.html", type: "score", tags: "IBW ideal body weight tidal volume ventilator settings 6 ml/kg ARDS lung protective height gender", desc: "Calculate IBW and 6 ml/kg tidal volume for ventilator setup." },

  // ── PAGES ───────────────────────────────────────────────────────────────────
  { title: "About Dr. Anmol Srivastava", url: "about.html", type: "page", tags: "about Dr Anmol Srivastava emergency medicine SGPGIMS ICU anaesthesiology critical care contact", desc: "Dr. Anmol Srivastava — Senior Resident Emergency Medicine, SGPGIMS Lucknow." },
  { title: "All ICU Topics", url: "topics.html", type: "page", tags: "topics ICU reference library clinical cardiology respiratory renal neuro infections supportive care", desc: "Full topic library — 22+ evidence-based critical care topics." },
];
